# Site settings
title: Serghei Mihailov
description: Personal page
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Serghei Mihailov
user_description: Software Engineer.
user_title: Software Engineer
email: mihailov.serghei.d@gmail.com
github_username:  SergheiMihailov

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
